### ISSUE TITLE
Players Unable to load canvas with NL Notes on it

### ISSUE THREAD

**Issue by zero127** [MrPrimate/NoteLicker#3]
**Describe the bug**
Players are unable to render canvas on maps containing Notelicker Notes. GM does not have the issue. Only players.

**To Reproduce**
1. Enable Notelicker, Libwrapper
2. Create a note on your Foundry DM client
3. Have a player log in with the map active, 
4. See as player upon login or navigation to map

**Expected behavior**
Logging in, or loading maps as one normally does (and ideally not -seeing- the notes from notelicker since i'm using them like a GM map key)

**Screenshots**
![image](https://github.com/MrPrimate/NoteLicker/assets/26309432/88353dee-1c24-4e5d-bd85-66c8a8ca25a5)
This is the error produced.

**Environment:**
 - Chrome Version 119.0.6045.124 (player tested using Edge, Firefox, Chrome, and Ripper's FVTT Client; identical results, browser independent)
 - Foundry v11 - 315 (Self Hosted)
 - Dnd5e 2.3.1
 - Module v 0.14
 - Yes, Tested with FTC, Libwrapper + Notelicker only, issue persisted

**Additional context**
I only just started using this this week, so i've only tested with 2 maps, but I have a map i've been using for a year, 
Console error, only one, i _think_.
```
Uncaught (in promise) Error: Directory modules/notelicker/storage does not exist or is not accessible in this storage location
    at a.<anonymous> (foundry.js:67108:43)
    at a.value (socket.js:532:17)
    at a.value (socket.js:459:22)
    at L.emit (index.mjs:136:20)
```
    
Overall, i feel like somebody else would have reported this if this wasn't something from the latest Foundry update. I know a handful of things got fiddled with there. No big rush, I can make do this weekend just using text for the dungeon i was doing this on. Have plenty of time just figured i'd drop this in the hat in case this wasn't just me. Feel free to close if its something weird with my system or something.

(edited to fix concole error because i pasted like a dumb.)

**Comment by MrPrimate** [comment]
I'm really struggling to replicate this. If you open the modules/notelicker/storage folder yourself, and are their icons there? (These should be generated for a page the first time a GM user visits a scene with notelicker enabled. (And the folder should always exist)

**Comment by zero127** [comment]
yeah, as a GM it works fine, but myself or my players cannot get into my world. May just be an old world or something. Unsure. I did make the map recently. We could connect on discord i could screenshare see if i have something messed up. If it helps, the icons its' using are the named ones, for example M1A Atrium results in an M1A icon for the note. but doesn't matter either way even a full-size note did it on a map of waterdeep that we've been using. If its' just me its no big deal, don't need the addon it was just really neat and very handy not to have to also add myself text labels but your time is worth more than the issue if its not an actual bug lol 

edit:
In the event it was an order of operations thing, i've tried:
- enable notelicker, navigate away from map, navigate to map, player logs in -> same result
- enable notelicker, player login, error happens -> navigate away (canvas doesnt load; f5 to refresh, canvas loads) -> navigate back -> same result.

So if its just me and you're able to use it fine its no biggy, let me know and we can either connect on discord (i'm on your server as dan127) or we can just close this. its certainly not a crucial issue, and one i can work around/without. Thanks for lookin into it thus far either way.

**Comment by MrPrimate** [comment]
Please reach out on Discord and we can take a look

**Comment by kiloforce** [comment]
Also running into this.  Recently added Note Licker to my world.  Works great for the DM, but player can't join, as getting this 'storage' error.

**Comment by MrPrimate** [comment]
> Also running into this. Recently added Note Licker to my world. Works great for the DM, but player can't join, as getting this 'storage' error.

I'm struggling to replicate this, can you reach out on discord so I can take a look?

This directory should always exist, as it's provided as part of the module install. When Notelicker runs when a GM runs it should create the images here. (If a player is just logged in, it will fallback to the default icon (or at least does here)).

This makes me think there maybe something odd going on with hosting, or someway of configuring the system I've not come across yet.

**Comment by zero127** [comment]
Best guess, honestly, kiloforce is your world really old? like pre-v9? I'm thinking of just compendium-ing all my stuff and getting a clean start. I've run into a bunch of stuff that neither Mr Primate or Tim Posney can replicate so i think its gotta be "us" lol... something funky in the world. 

I finally updated to dnd5e 2.4 yesterday and i had something as inane as an ancient buff on a dead actor on a map we hadn't been to in months stopping the update with a hard error. Sometimes, i think its best to just clean up; gonna try that this week, i think. So, that's what im going to do! Sorry for the trouble.

**Comment by kiloforce** [comment]
It's a newly created instance of a world, but it's probably an older initially created world.  It's one I bought through Forge Marketplace (https://forge-vtt.com/bazaar/package/spcm-ghoul-island-saga)

**Comment by kiloforce** [comment]
So out of curiosity I renabled the module again today, and my test player is able to join, without the above error.  If I look in the modules/notelicker folder, the storage folder is there, and is older than the date I reported the issue above (so it didn't get created after reporting the issue).  But, I have updated/restarted the Foundry instance several times since then.  Maybe the foundry instance need a restart to "unstick" what ever caused the random issue?

```
kiloforce@foundry:~/vtt/data/Data/modules/notelicker$ ls -la -n
total 36
drwxrwxr-x   7 1002 1002 4096 Dec 18 10:56 .
drwxrwxr-x 115 1002 1002 4096 Jan 12 20:04 ..
drwxrwxr-x   2 1002 1002 4096 Dec 18 10:56 css
drwxrwxr-x   2 1002 1002 4096 Dec 18 10:56 dist
drwxrwxr-x   2 1002 1002 4096 Dec 18 10:56 lang
-rw-rw-r--   1 1002 1002 1070 Dec 18 10:56 LICENSE.md
-rw-rw-r--   1 1002 1002 1317 Dec 18 10:56 module.json
drwxrwxr-x   2 1002 1002 4096 Dec 18 11:21 storage
```

Weird.

**Comment by kiloforce** [comment]
Umm... I this was working last week... and it's back...

![image](https://github.com/MrPrimate/NoteLicker/assets/433058/64b32568-f517-4700-be68-fcb389712e08)

**Comment by Peach774** [comment]
SO uh - I'm also running into this issue, but only one of my players has this problem. IDK why and its only one specific map.
